/**
 * Bake the static assets into a TypeScript module.
 *
 * The schema, the migrations, the curriculum and the browser runtime are all files
 * on disk today, found by walking up from `import.meta.url`. That works from a
 * checkout and breaks the moment primer is a single packaged binary, where there is
 * no `src/` to walk to — and it breaks as a missing-file crash at startup rather
 * than anything a person could act on.
 *
 * Disk still wins when it is there, so editing a curriculum file in a checkout takes
 * effect immediately without regenerating anything. This is the fallback.
 *
 *   node scripts/embed-assets.mjs
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'src');

const quote = (text) => JSON.stringify(text);

const schema = readFileSync(join(src, 'db', 'schema.sql'), 'utf8');
const runtime = readFileSync(join(src, 'surface', 'runtime.js'), 'utf8');

const migrationsDir = join(src, 'db', 'migrations');
const migrations = readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.sql'))
  .sort()
  .map((name) => [name, readFileSync(join(migrationsDir, name), 'utf8')]);

const curriculumDir = join(src, 'curriculum');
const curriculum = readdirSync(curriculumDir)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .map((name) => [name, readFileSync(join(curriculumDir, name), 'utf8')]);

const out = `// Generated by scripts/embed-assets.mjs — do not edit.
//
// The originals live in src/db, src/curriculum and src/surface. These copies exist
// so primer still works when there is no source tree beside it: a packaged binary,
// a global install, anywhere the path-probing would come up empty.

export const SCHEMA_SQL = ${quote(schema)};

export const RUNTIME_JS = ${quote(runtime)};

export const MIGRATIONS: ReadonlyArray<readonly [string, string]> = [
${migrations.map(([name, body]) => `  [${quote(name)}, ${quote(body)}],`).join('\n')}
];

export const CURRICULUM: ReadonlyArray<readonly [string, string]> = [
${curriculum.map(([name, body]) => `  [${quote(name)}, ${quote(body)}],`).join('\n')}
];
`;

mkdirSync(join(src, 'generated'), { recursive: true });
writeFileSync(join(src, 'generated', 'assets.ts'), out, 'utf8');

const bytes = Buffer.byteLength(out);
console.log(
  `embedded ${migrations.length} migrations, ${curriculum.length} curriculum packs, ` +
    `schema and runtime (${Math.round(bytes / 1024)}KB)`,
);
